def print_number(num):
    print(num, end='')
print_number(8)
print_number(8)
print_number(0)
print_number(0)
print_number(5)
print_number(5)
print_number(5)
print_number(3)
print_number(5)
print_number(3)
print_number(5)
def print_letter(letter):
    print(letter, end='')
print_letter('S')
print_letter('k')
print_letter('y')
print_letter('P')
print_letter('r')
print_letter('o')